name: Static-Pages-CI


# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events
  pull_request:
    branches: ['*']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  staticpages:
    name: Static Pages CI
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@main

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.9'
          architecture: 'x64'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r ./requirements.txt
      - name: Render Static Pages
        run: python3 build.py

      - name: Deploy to GitHub Pages
        runs-on: ubuntu-latest
        steps:
                # Use avinal/github-pages-deploy-action@<latest-release-tag> for latest stable release
                # Do not change the line below except the word main with tag number maybe
          - uses: avinal/github-pages-deploy-action@main
            with:
              # GitHub access token with Repo Access
              GITHUB_TOKEN: ${{ github.token }}
              # For JavaDoc - "java"
              # For python write python package and additional packages if any - "python3 python3-pip" 
              LANGUAGE: "<python3>"
              # Write make command to generate html e.g.- "make html"
              MAKE_COMMAND: "make html"
              # Write the branch name for storing github pages source 
              PAGES_BRANCH: "gh-pages"
              # Write the branch name having source files for site/documentation
              BUILD_FROM: "master"
              # Write the name of the output folder where generated html is stored by makefile.
              DOCS_FOLDER: "docs"
