name: Static-Pages-CI


# Controls when the workflow will run
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  staticpages:
    name: Static Pages CI
    runs-on: ubuntu-latest
    env: 
      prod: True

    steps:
      - name: Clone repo
        uses: actions/checkout@main

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.9'
          architecture: 'x64'
    
      - name: Install Python dependencies
        run: python3 -m pip install -r ./requirements.txt

      - name: Render Static Pages
        run: python3 build.py
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          full_commit_message: ${{ github.event.head_commit.message }}
